version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /
  script: main.app

- url: /hello.*
  script: hello.app

- url: /rot13.*
  script: rot13.app

- url: /signup.*
  script: signUp.app

- url: /blog.*
  script: blog.app

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico




